(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["addon-entry-tw-remove-feedback"],{

/***/ "./node_modules/css-loader/index.js!./node_modules/scratch-gui/src/addons/addons/tw-remove-feedback/remove-feedback.css":
/*!*********************************************************************************************************************!*\
  !*** ./node_modules/css-loader!./node_modules/scratch-gui/src/addons/addons/tw-remove-feedback/remove-feedback.css ***!
  \*********************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

exports = module.exports = __webpack_require__(/*! ../../../../../css-loader/lib/css-base.js */ "./node_modules/css-loader/lib/css-base.js")(false);
// imports


// module
exports.push([module.i, "a[class^=\"menu-bar_feedback-link_\"] {\n  display: none;\n}\n", ""]);

// exports


/***/ }),

/***/ "./node_modules/scratch-gui/src/addons/addons/tw-remove-feedback/_runtime_entry.js":
/*!*****************************************************************************************!*\
  !*** ./node_modules/scratch-gui/src/addons/addons/tw-remove-feedback/_runtime_entry.js ***!
  \*****************************************************************************************/
/*! exports provided: resources */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "resources", function() { return resources; });
/* harmony import */ var _css_loader_remove_feedback_css__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! css-loader!./remove-feedback.css */ "./node_modules/css-loader/index.js!./node_modules/scratch-gui/src/addons/addons/tw-remove-feedback/remove-feedback.css");
/* harmony import */ var _css_loader_remove_feedback_css__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_css_loader_remove_feedback_css__WEBPACK_IMPORTED_MODULE_0__);
/* generated by pull.js */

const resources = {
  "remove-feedback.css": _css_loader_remove_feedback_css__WEBPACK_IMPORTED_MODULE_0___default.a
};

/***/ })

}]);
//# sourceMappingURL=addon-entry-tw-remove-feedback.index.js.map